import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-deals',
  templateUrl: 'deals.html'
})
export class DealsPage {
  deals = [
    [1, "1", "Draw & resolve Event card"], 
    [2, "1", "+3 Threat"], 
    [3, "1", "Place 2 Outage tokens"], 
    [4, "1", "-2 Entertainment*"], 
    [5, "1", "-2 Energy*"], 
    [6, "1", "-2 Tech*"], 
    [7, "1", "-2 Consumables*"], 
    [8, "1", "Place 2 Illness tokens"], 
    [9, "2", "Draw & resolve Event card"], 
    [10, "2", "Move all Human First units"], 
    [11, "2", "Discard 3 Action cards"], 
    [12, "2", "Discard 2 Asset cards"], 
    [13, "2", "-1 Entertainment*"], 
    [14, "2", "Place 1 Illness token"], 
    [15, "2", "Discard 1 Asset"], 
    [16, "2", "+2 Threat"], 
    [17, "2", "-1 credits*"], 
    [18, "2", "-1 Tech*"], 
    [19, "2", "-1 Consumables*"], 
    [20, "2", "Discard 2 Action cards"], 
    [21, "2", "Move all Human First units"], 
    [22, "2", "-1 Energy*"], 
    [23, "2", "Place 1 Org crime unit"], 
    [24, "2", "Place 1 Human First unit"], 
    [25, "2", "-1 Tech*"], 
    [26, "3", "-1 Consumables*"], 
    [27, "3", "Place 1 Illness token"], 
    [28, "3", "Move all Org crime units"], 
    [29, "3", "Place 1 Outage token"], 
    [30, "3", "Discard 2 Action cards"], 
    [31, "3", "Discard 1 Asset"], 
    [32, "3", "-1 Entertainment*"], 
    [33, "3", "Place 1 Illness token"], 
    [34, "3", "Discard 1 Asset"], 
    [35, "3", "+1 Threat"], 
    [36, "3", "-1 Credits*"], 
    [37, "3", "Place 1 Org crime unit"], 
    [38, "3", "Place 1 Human First unit"], 
    [39, "3", "Move all Org crime units"], 
    [40, "3", "Move all Human First units"], 
    [41, "3", "-1 Entertainment*"], 
    [42, "3", "Place 1 Illness token"], 
    [43, "3", "+1 Threat"], 
    [44, "3", "Discard Investment card"], 
    [45, "3", "-1 Tech*"], 
    [46, "3", "-1 Consumables*"], 
    [47, "3", "Place 1 Illness token"], 
    [48, "3", "-1 Energy"], 
    [49, "3", "Discard 2 Action cards"], 
    [50, "3", "Discard 1 Asset"], 
    [51, "3", "-1 Consumables*"], 
    [52, "3", "Discard 2 Action cards"], 
    [53, "3", "Discard 1 Asset card"], 
    [54, "3", "-1 Entertainment*"], 
    [55, "3", "Place 1 Illness token"], 
    [56, "4", "Discard 1 Asset"], 
    [57, "4", "+2 Threat"], 
    [58, "4", "-1 credits*"], 
    [59, "4", "-1 Tech*"], 
    [60, "4", "-1 Consumables*"], 
    [61, "4", "Discard 2 Action cards"], 
    [62, "4", "Move all Human First units"], 
    [63, "4", "-1 Energy*"], 
    [64, "4", "Place 1 Org crime unit"], 
    [65, "4", "Place 1 Human First unit"], 
    [66, "4", "-1 Tech*"], 
    [67, "4", "-1 Consumables*"], 
    [68, "4", "Place 1 Illness token"], 
    [69, "4", "Remove 1 Development token"], 
    [70, "4", "Move all Human First units"], 
    [71, "4", "Discard 2 Action cards"], 
    [72, "4", "Discard 1 Asset"], 
    [73, "4", "-1 Entertainment*"], 
    [74, "4", "Place 1 Illness token"], 
    [75, "4", "Discard 1 Asset"], 
    [76, "4", "+1 Threat"], 
    [77, "4", "-1 credits*"], 
    [78, "4", "Place 1 Org crime unit"], 
    [79, "4", "Place 1 Human First unit"], 
    [80, "4", "Move all Org crime units"], 
    [81, "4", "Remove 1 Development token"], 
    [82, "4", "-1 Entertainment*"], 
    [83, "4", "Place 1 Illness token"], 
    [84, "4", "+1 Threat"], 
    [85, "4", "Discard Investment card"], 
    [86, "5", "-1 Tech*"], 
    [87, "5", "-1 Consumables*"], 
    [88, "5", "Place 1 Illness token"], 
    [89, "5", "-1 Energy"], 
    [90, "5", "Discard 2 Action cards"], 
    [91, "5", "Discard 1 Asset"], 
    [92, "5", "Discard 2 Action cards"], 
    [93, "5", "Remove 1 Development token"], 
    [94, "5", "-1 Energy*"], 
    [95, "5", "Discard 1 Asset"], 
    [96, "6", "-1 Credits*"], 
    [97, "6", "-1 Tech*"], 
    [98, "6", "-1 Consumables*"], 
    [99, "6", "Place 1 Illness token"], 
    [100, "7", "Place 1 Outage token"] ];

  currentDeal = null;
  constructor(public navCtrl: NavController) {    
  }

  createCounterOffer() {
    this.currentDeal = this.deals[Math.floor(Math.random() * this.deals.length)];
  }
}
